---

- name: copy redis script
  template:
    src: "redis"
    dest: /usr/local/bin/redis
    mode: 0755
    owner: root
    group: root

- name: copy redis script
  template:
    src: "redis.service"
    dest: /etc/systemd/system/redis.service
    mode: 0644
    owner: root
    group: root

- name: reload systemd
  command: systemctl daemon-reload
  notify:
    - restart redis

- name: wait for redis to become ready
  wait_for:
      host: "{{ redis_server_bind }}"
      port: "{{ redis_server_port }}"
      state: started
      delay: 5
      connect_timeout: 15
      timeout: 300
